### ISSUE TITLE
recognitionTask error

### ISSUE THREAD

**Issue by FJLopezGarcia** [ikwattro/ionic-speechy#1]
HI @ikwattro 
I have installed the App and I have emulated the App in an IOS emulator but it seems there is an error. below the log from Xcode. Any idea? thanks a lot!!

recognitionTask error: Error Domain=kAFAssistantErrorDomain Code=1101 "(null)"
2017-06-20 17:07:20.803 MyApp[34177:4698212] ERROR: Error Domain=kAFAssistantErrorDomain Code=1101 "(null)"

**Comment by ikwattro** [comment]
hi @FJLopezGarcia 

you cannot test speech recognition in an emulator, transfering it to a device is a matter of clicks

**Comment by FJLopezGarcia** [comment]
I will try and let you know!! thanks for your quick answer!!

**Comment by FJLopezGarcia** [comment]
It works on real devices!! thanks!!

**Comment by ikwattro** [comment]
Great you could make it work !
