### ISSUE TITLE
How to avoid google auto populate window?

### ISSUE THREAD

**Issue by BUHARIMOHAMEDISMAIL** [ikwattro/ionic-speechy#2]
I tried this it's working good.
When i click start listening button auto popup will be appeared it contain the  message as "Try say something". i need to remove that popup.
Let me know how to remove it.
please assist me

**Comment by texano00** [comment]
I think there's no workaround because is the native google assistant.

**Comment by BUHARIMOHAMEDISMAIL** [comment]
Okay.
Thanks for you reply.
